app/models/user.py
class User():

    __tablename__ = 't_users'

    def __init__(self):
        pass

app/forms/user.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
import wtforms.validators as validators


class SignUp(Form):
    first_name = StringField(
        'Name', validators=[validators.input_required(), validators.length(min=2)])
    last_name = StringField('Surname', validators=[
                            validators.input_required(), validators.length(min=2)])
    phone = StringField('Phone number', validators=[
                        validators.input_required(), validators.length(min=6)])
    email = StringField('Email address', validators=[
                        validators.input_required(), validators.email()])
    password = PasswordField('Password', validators=[
        validators.input_required(), validators.length(min=6), validators.equal_to('confirm', 'Passwords must match.')])
    confirm = PasswordField('Confirm password')


class SignIn(Form):
    email = StringField('Email address', validators=[
                        validators.input_required(), validators.email()])
    password = PasswordField('Password', validators=[
        validators.input_required(), validators.length(min=6)])

app/__init__.py
from app.libraries.session.usersession import User
from flask import Flask ## import Flask dari package flask
from flask import session, redirect, url_for
import flask_login

app = Flask(__name__)

# Setup the app with config.py file
app.config.from_object('app.config')

# Setup the logger
from app.logger_setup import logger

# Set secret key
app.secret_key = app.config['SECRET_KEY']

# Import the controllers
from app.controllers import *

# TODO: add your blueprint page in here
app.register_blueprint(user.userbp)

# login manager
login_manager = flask_login.LoginManager()
login_manager.init_app(app)

# TODO: authenticate the user session
@login_manager.user_loader
def user_loader(id):
    if 'usersession' in session:
        usersession = session['usersession']
        print(usersession)
    
    # authenticate the roles
    # redirect to unathorized if not passed

    return User(id)

@login_manager.request_loader
def request_loader(request):
    pass

@login_manager.unauthorized_handler
def unauthorized_handler():
    return redirect(url_for('userbp.signin'))

app/controllers/__init__.py
from os.path import dirname, basename, isfile, join
import glob

modules = glob.glob(join(dirname(__file__), "*.py"))
__all__  = [ basename(f)[:-3] for f in modules if  isfile(f) and  not f.endswith('__init__.py')]

app/controllers/handler.py
from flask import (
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for
)
from app import app

@app.route('/404', methods = ['GET'])
def handler404():
    return render_template('handler/404.html', title="404 - rocket.saas")

app/controllers/indexcontroller.py
from flask import (
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for
)
from app import app

@app.route('/', methods = ['GET'])
@app.route("/index")
def index():
    return render_template('index.html')

app/controllers/main.py
from flask import (
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for
)
import flask_login
from app import app

@app.route('/', methods = ['GET'])
@app.route("/index")
def index():
    return render_template('index.html', title="rocket.saas")


@app.route('/home', methods = ['GET'])
@flask_login.login_required
def home():
    return render_template('home.html', title="rocket.saas")

app/controllers/user.py
from flask import (
    Blueprint,
    render_template, 
    g,
    request,
    session,
    redirect,
    url_for,
    flash
)
import flask_login

from app import app
from app.forms import user as user_forms
import json
from json import dumps

from app.libraries.session import usersession as USession

# Create a user blueprint
userbp = Blueprint('userbp', __name__, url_prefix='/user')


@userbp.route('/signup', methods=['GET', 'POST'])
def signup():
    form = user_forms.SignUp(request.form)

    # form submit
    if request.method == 'POST' and form.validate():
        return redirect(url_for('index'))

    return render_template('user/signup.html', form=form, title='Sign Up')


@userbp.route('/signin', methods=['GET', 'POST'])
def signin():
    # if already login, redirect to home
    if 'usersession' in session and session["usersession"] is not None:
        return redirect(url_for('home'))

    form = user_forms.SignIn(request.form)

    # initialize sample input
    if request.method=="GET":
        form.email.data = "demo@rocket.com"

    # form submit
    if request.method=="POST" and form.validate():
        if form.email.data == "demo@rocket.com" and form.password.data == "demodemo":
            # process the login manager session
            user = USession.User()
            # TODO: place your user / account data
            user.name = form.email.data
            user.email = form.email.data

            # save to session
            session["usersession"] = user.__dict__
            flask_login.login_user(user)
            return redirect(url_for('home'))
        else:
            flash('Invalid account.', 'negative')
            return redirect(url_for('userbp.signin'))

    return render_template('user/signin.html', form=form, title='Sign In')


@userbp.route('/signout')
@flask_login.login_required
def signout():
    flask_login.logout_user()
    session["usersession"] = None
    flash('Succesfully signed out.', 'positive')
    return redirect(url_for('index'))


@userbp.route('/profile')
@flask_login.login_required
def profile():
    return render_template('user/profile.html', title='Profile')


@userbp.route('/browse')
@flask_login.login_required
def browse():
    return render_template('user/browse.html', title='Users')

app/templates/frame/navigation.html
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle">
        <i class="hamburger align-self-center"></i>
    </a>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
            <li class="nav-item dropdown">
                <a class="nav-icon dropdown-toggle d-inline-block d-sm-none" href="#" data-bs-toggle="dropdown">
                    <i class="align-middle" data-feather="settings"></i>
                </a>
                <a class="nav-link dropdown-toggle d-none d-sm-inline-block" href="#" data-bs-toggle="dropdown">
                    <span class="text-dark">{{ session["usersession"].name }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a class="dropdown-item" href="{{ url_for('userbp.profile') }}"><i class="align-middle me-1"
                            data-feather="user"></i> Profile</a>
                    <div class="dropdown-divider"></div>
                    {% if session["usersession"].admin %}
                    <a class="dropdown-item" href="{{ url_for('userbp.browse') }}">Manage User</a>
                    <a class="dropdown-item" href="/roles">Manage Role</a>
                    <a class="dropdown-item" href="/server">Manage Server</a>
                    <a class="dropdown-item" href="/menu">Manage Menu</a>
                    <div class="dropdown-divider"></div>
                    {% endif %}
                    <a class="dropdown-item" href="{{ url_for('userbp.signout') }}"><i class="align-middle me-1" data-feather="log-out"></i>Logout</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

app/templates/home.html
{% extends 'layouts/main.html' %}

{% block content %}

<main>
    <!-- dashboard -->
    <section>
        <div class="container mt-2 mb-2">
        </div>
    </section>
</main>

{% endblock %}

app/templates/index.html
{% extends 'layouts/home.html' %}

{% block content %}

<main>
    <nav class="navbar navbar-light">
        <!-- Container wrapper -->
        <div class="container-fluid">
            <a class="navbar-brand">{{ title }}</a>
            <div class="form-inline">
                <a href="/user/signin" class="btn btn-primary">Sign In</a>
            </div>
        </div>
    </nav>

    <header></header>

    <!-- information banner -->
    <section>
        <div class="container mt-2 mb-2">
            <h1 class="banner-title">Decentralized, <br />application</h1>
            <p>The main objective of decentralised was to involve peoples' participation.</p>

            <a href="/user/signup" class="btn btn-primary">Get Started</a>
        </div>
    </section>

</main>

{% endblock %}

app/templates/layouts/home.html
<!DOCTYPE html>
{% import "macros.html" as m %}
<html lang="en">

<body id="container">
	<div id="header">
		{% block head %}
		<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
		<meta charset="UTF-8">
		<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
		<!-- jQuery -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
		<!-- Semantic Main CSS -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css" />
		<!-- Semantic Reset CSS -->
		<link rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/components/reset.min.css" />
		<!-- Semantic Menu CSS -->
		<link rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/components/menu.min.css" />
		<!-- Main Semantic JS  -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
		<!-- Custom CSS -->
		<link rel="stylesheet" href="{{ url_for('static', filename='css/light.css') }}">
		<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
		<!-- Browser tab name -->
		<title>{{ title }}</title>
		<!-- Navbar -->
		{% endblock %}
	</div>
	<!-- Message flashing -->
	{% with messages = get_flashed_messages(with_categories=true) %}
	{% if messages %}
	<div class="messages-block">
		{% for category, message in messages %}
		<div class="ui {{ category }} message flash">{{ message }}</div>
		{% endfor %}
	</div>
	{% endif %}
	{% endwith %}
	<div id="body" class="body">
		{% block content %}{% endblock %}
	</div>
	<div id="footer">
		<div class="ui divided horizontal footer link list">
			<div class="item">
				sluvie
			</div>
			<div class="item">
				<a href="https://github.com/sluvie"><i class="github icon"></i></a>
			</div>
		</div>
	</div>
	</div>
</body>

</html>

app/templates/macros.html
<!-- Render a WTForm form's field (with it's possible associated errors) from a WTForms form -->
{% macro render_field(field) %}
<div class="field">
    <dt>{{ field.label }}
    <dd>{{ field(**kwargs)|safe }}
</div>
{% if field.errors %}
<ul>
    {% for error in field.errors %}
    <li class="form-error">{{ error }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endmacro %}

app/templates/user/browse.html
{% extends 'layouts/main.html' %}

{% block content %}

<main>
    <!-- browse user -->
    <section>
        <div class="container mt-2 mb-2">
            <h3>{{ title }}</h3>

            <div class="card flex-fill">
                <div class="card-header">
                    <div class="card-actions float-end">
                        <div class="dropdown position-relative"></div>
                    </div>
                </div>
                <div class="card-body">
                    <div id ="grid-main"></div>
                </div>
            </div>
        </div>
    </section>
</main>

{% endblock %}

{% block scriptcustom %} 

<script src="{{ url_for('static', filename='js/page/user/data.js') }}"></script>
<script src="{{ url_for('static', filename='js/page/user/browse.js') }}"></script>

{% endblock %}

app/templates/user/profile.html
{% extends 'layouts/main.html' %}

{% block content %}

<main>
    <!-- information account -->
    <section>
        <div class="container mt-2 mb-2">
            <h2>Profile</h2>
        </div>
    </section>
</main>

{% endblock %}

app/templates/user/signin.html
{% extends "layouts/home.html" %}

{% block content %}

<div class="container mt-2 mb-2">

	<div class="form-signin">

		<div class="row card-signin">
			<div class="card-signin-left col">
				<div class="card-signin-title">
					<h1>Sign In</h1>
				</div>

				<span class="text-danger">use the password : demodemo</span>

				<form class="form" action="{{ url_for('userbp.signin') }}" method="post">
					{{ m.render_field(form.email, class='form-control') }}
					{{ m.render_field(form.password, class='form-control') }}
					{{ form.csrf_token }}
					<button class="btn btn-large btn-block btn-primary form-control mt-3" type="submit">Sign In</button>
				</form>
			</div>

			<div class="card-signin-right col">
				<div class="row">
					<h1 class="col-12"co>Hello, Friend!</h1>
					<h6 class="col-12">Enter your personal details and start journey with us</h6>
					<a href="{{ url_for('userbp.signup') }}" class="btn btn-large btn-block btn-dark mt-3">Sign Up</a>
				</div>
			</div>
		</div>

	</div>

</div>

{% endblock %}

app/templates/user/signup.html
{% extends "layouts/home.html" %}

{% block content %}

<div class="container mt-2 mb-2">

    <div class="form-signup">
        <div class="card-signup">
            <div class="card-signup-title">
                <h1>Create Account</h1>
                <span>Already have an account? <a href="/user/signin">Sign In</a></span>
            </div>

            <form class="form" action="/user/signup" method="post">
                {{ m.render_field(form.first_name, class='form-control') }}
                {{ m.render_field(form.last_name, class='form-control') }}
                {{ m.render_field(form.phone, class='form-control') }}
                {{ m.render_field(form.email, class='form-control') }}
                {{ m.render_field(form.password, class='form-control') }}
                {{ m.render_field(form.confirm, class='form-control') }}
                {{ form.csrf_token }}
                <button class="btn btn-large btn-block btn-primary form-control mt-3" type="submit">Sign Up</button>
            </form>

        </div>
    </div>

</div>

{% endblock %}